export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const GET_CART_DATA = "GET_CART_DATA";
export const GET_CART_DATA_FAILURE = "GET_CART_DATA_FAILURE";
export const GET_CART_DATA_SUCCESS = "GET_CART_DATA_SUCCESS";
export const ADD_TO_CART = "ADD_TO_CART";


export const DELETE_CART_DATA = "DELETE_CART_DATA";